name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run:
        sudo apt update
        sudo apt install --no-install-recommends gfortran
   
    - name: configure
      run: ./configure
      
    - name: build debug
      run: make all
      
    - name: build release
      run: make -DEBUG=0 all
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
